summer2015/sandbox/config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'sessions/new'

  root 'pages#home'

  get '/contact' => 'pages#contact'

  get '/about' => 'pages#about'

  resources :meals

  resources :movies

  resources :cars

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

end

summer2015/sandbox/app/models/car.rb
class Car < ActiveRecord::Base
end

summer2015/sandbox/app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :meal
end

summer2015/sandbox/app/models/meal.rb
class Meal < ActiveRecord::Base
  has_many :ingredients
  belongs_to :person
  validates :name, presence: true, uniqueness: true # checking the presence of name
end

summer2015/sandbox/app/models/movie.rb
class Movie < ActiveRecord::Base
end

summer2015/sandbox/app/models/person.rb
class Person < ActiveRecord::Base
  has_many :meals
end

summer2015/sandbox/app/models/user.rb
class User < ActiveRecord::Base

  enum membership: [:basic, :plus, :pro]
  has_secure_password


end

summer2015/sandbox/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.where(id: session[:user_id]).first
  end
  helper_method :current_user
  
end

summer2015/sandbox/app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :find_car, only: [:edit, :update, :show, :destroy]

  
  def index
    @cars = Car.all 
  end
 
  def new
    @car = Car.new  
  end

  
  def create
    @car = Car.new(car_params)
    @car.save   
    if @car.save
      
      redirect_to cars_path  
    else
      
      render :new 
    end    
  end

  
  def edit
      
  end

  
  def update
    if @car.update(car_params) 
      redirect_to cars_path
    else
      render :edit
    end
  end

  
  def show
  end

  
  def destroy
    @car.destroy  
    redirect_to cars_path
  end

  private
  def car_params
    params.require(:car).permit(:name, :company)  
  end 

  private 
  def find_car
    @car = Car.find(params[:id]) 
  end 

end

summer2015/sandbox/app/controllers/meals_controller.rb
class MealsController < ApplicationController

  def index
    @meals = Meal.all
  end

  def show
    @meal = Meal.find(params[:id])
  end

  def new
    @meal = Meal.new
  end

  def create
    @meal = Meal.new(meal_params)
    @meal.save
    if @meal.save
      redirect_to meals_path
    else
      render :new
    end
  end

  def edit
    @meal = Meal.new(meal_params)
  end

  def destroy
    @car.destroy  
    redirect_to cars_path
  end

  private
  def meal_params
    params.require(:meal).permit(:name, :calories, :restuarant)
  end
end

summer2015/sandbox/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :find_movie, only: [:edit, :update, :show, :destroy]

  # to display a collection of movies
  def index
    @movies = Movie.all # here Movie is singular for it is a model.
  end

  # to display a form create a movie. new goes to create it means  it is related with create
  def new
    @movie = Movie.new  # here it is singular for new form is created for new movie, one movie
  end

  #the logic to store the new data into the database
  def create
    @movie = Movie.new(movie_params)
    @movie.save   # (for the save goes with instance variable we can not use is with Movie model.) params have all the access to the data in the database.for we don't have any data in the database for create 
    if @movie.save
      #if returns true. Do stuff 
      redirect_to movies_path  # there is no create page in the database so we need to render or redirect the info. in this we are redircting the info to the index page. (@movie.id) do this if you want to  redirect the to the show page.
    else
      #if returns false. Do stuff
      render :new # it displays the form again with the info that user gave in a new page
      #redirect_to new_movie_path we can do this but it will give a new form that is empty. user have to type everything again. so render is prefered.
    end    
  end

  # to display a form to update an existing movie
  def edit
      # if this didn't work it will display an error 404. (page not found) error by default.
  end

  # the logic to alter the data of an existing movie in the database. it overwrite the existing data with the update.
  def update
    if @movie.update(movie_params) # here update is built in methods of rails that is deffined bu ActiceRecord. 
      redirect_to movies_path
    else
      render :edit
    end
  end

  # to display data from a specific movie
  def show
  end

  # to remove data from the database
  def destroy
    @movie.destroy  
    redirect_to movies_path
  end

  private
  def movie_params
    params.require(:movie).permit(:title, :released_at)  # strong params that prevents the user to push or insert the data other than title and released_at info.
  end 

  private 
  def find_movie
    @movie = Movie.find(params[:id]) #singular of movie that is @movie not @movies.
  end 

end

summer2015/sandbox/app/controllers/pages_controller.rb
  class PagesController < ApplicationController

  def home
  end

  def contact
  end

  def about
  end
end

summer2015/sandbox/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.where(username: params[:username]).first
    if @user.present? && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Welcome , you've got it"
    else
      flash[:alert] = "boo. that didn't work"
      render :new
    end
  end

 def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

summer2015/sandbox/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create 
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to(root_path, notice: 'YAY! welcome!!!!')
    else
      flash[:alter] = "boo. that didn't work"
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :membership)
  end
end

summer2015/sandbox/app/helpers/application_helper.rb
module ApplicationHelper

  def active_for_page(scope)
    controller, action = *scope.split('#')
    if params[:controller] == controller && params[:action] == action
      return "active"
    end
  end

  def user_signed_in?
    current_user.present?
  end
end

summer2015/sandbox/app/helpers/sessions_helper.rb
module SessionsHelper
end

summer2015/sandbox/app/helpers/users_helper.rb
module UsersHelper
end

summer2015/sandbox/app/views/meals/_form.html.erb
 <div class="form-group">
  <p> name: <%= f.text_field(:name) %></p>
  <p>calories: <%= f.text_field(:calories) %></p>
  <p>restuarant: <%= f.text_field(:restuarant) %></p>
</div>

summer2015/sandbox/app/views/meals/edit.html.erb
<%= form_for(@meal) do |f| %>
 <%= render('form', f: f) %>
  <p><%= f.submit('Save', class: 'btn btn-sucess') %></p>
<% end %>

summer2015/sandbox/app/views/meals/index.html.erb
<!-- Meals page!

I have  @meals.count  meals!

<div class="">

   @meals.each do |meal| 
    <p> link_to(meal.name, meal_path(meal.id)) </p>
   end 
  
</div> -->
<div class="pull-right">
  <a href="<%= new_meal_path %>" class="btn btn-lg btn-success">
    <span class="glyphicon glyphicon-plus">
    </span>
  </a>
</div>

<h1 class="pages-header">All the Meals</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Calories</th>
      <th>Restaurant</th> 
      <th>Prep-time</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @meals.each do |meal| %>
    <tr>
      <td><%= link_to(meal.name, meal_path(meal.id)) %></td>
      <td><%= meal.calories %></td>
      <td><%= meal.restuarant %></td>
      <td><%= meal.prep_time %></td>
      <td>
        <a href="<%= edit_meal_path(meal.id) %>" class="btn btn-warning">
          <span class="glyphicon glyphicon-pencil"></span>
        </a>
        <a href="<%= meal_path(meal.id) %>" class ="btn btn-danger" data-method="delete">
          <span class="glyphicon glyphicon-trash"></span>
        </a>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

summer2015/sandbox/app/views/meals/new.html.erb
<%= form_for(@meal) do |f| %>
  <%= render('form', f: f) %>
  <p><%= f.submit('Save', class: 'btn btn-sucess') %></p>
<% end %>

summer2015/sandbox/app/views/meals/show.html.erb
<h1><%= @meal.name %></h1>

<h2><%= debug(params[:action]) %></h2>